name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Continuous Integration ${{ matrix.build_type }} ${{ matrix.toolset_name }}
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        toolset_name: [MSVC, Clang]
        build_dll: [false, true]
        include:
          - toolset_name: MSVC
            toolset: v142
          - toolset_name: Clang
            toolset: ClangCL
          - build_dll: false
            additional_opts: -DBUILD_OVERLUNKY=ON -DBUILD_INFO_DUMP=ON -DBUILD_SPEL2_DLL=OFF
          - build_dll: true
            additional_opts: -DBUILD_OVERLUNKY=OFF -DBUILD_INFO_DUMP=OFF -DBUILD_SPEL2_DLL=ON

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -A x64 -T ${{ matrix.toolset }} ${{ matrix.additional_opts }}

      - name: Build
        run: |
          cd build
          cmake --build . --config ${{ matrix.build_type }} --target ALL_BUILD
